# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 06:04
from __future__ import unicode_literals

import contact_verification.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[contact_verification.validators.PhoneNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='contactverification',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[contact_verification.validators.PhoneNumberValidator()]),
        ),
        migrations.AlterUniqueTogether(
            name='contactverification',
            unique_together=set([('country_number', 'phone_number')]),
        ),
    ]
