# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_verification', '0004_auto_20170509_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([]),
        ),
    ]
